import LayoutClientWrapper from "./_components/LayoutClientWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import { ApiProvider } from "./_provider/api";
import { yekanBakh } from "@/lib/fonts";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tanbaku",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/img/logo-PWA.png", sizes: "192x192", type: "image/png" },
      { url: "/img/logo-PWA.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/img/logo-PWA.png",
    apple: "/img/logo-PWA.png",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} antialiased`}
      >
        <ApiProvider>
          <LayoutClientWrapper>
            <main className="pb-44 max-w-lg w-full mx-auto">
              {children}
              <Toaster />
            </main>
          </LayoutClientWrapper>
        </ApiProvider>
      </body>
    </html>
  );
}
