import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { yekanBakh } from "@/lib/fonts";
import Head from "next/head"; // Import next/head to add meta tag
import LayoutClientWrapper from "./_components/LayoutClientWrapper";
import { ApiProvider } from "./_provider/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yekanBakh.variable} antialiased`}
      >
        {/* Add the meta tag for viewport inside the <Head> */}
        <Head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
          />
        </Head>
        <ApiProvider>
          <LayoutClientWrapper>
            <main className="pb-44 max-w-lg w-full mx-auto">
              {children}
              <Toaster />
            </main>
          </LayoutClientWrapper>
        </ApiProvider>
      </body>
    </html>
  );
}
