import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { IconShoppingCart, IconMenu2 } from "@tabler/icons-react";
import LogoIcon from "../icons/logo";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* Navbar */}
        <Navbar/> 

        <main className="flex-grow p-4 rounded-4xl mt-20 pb-40">
          {children}
        </main>

        {/* اضافه کردن فوتر */}
        <Footer />
      </body>
    </html>
  );
}
